#
# Module manifest for module 'PSEverything'
#
# Generated by: sgustafsson
#
# Generated on: 2015-03-18
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PSEverything.dll'

# Version number of this module.
ModuleVersion = '2.1'

# ID used to uniquely identify this module
GUID = 'f262ec02-4a88-49e5-94da-e25aab9cbf7a'

# Author of this module
Author = 'Staffan Gustafsson'

# Company or vendor of this module
CompanyName = 'PowerCode Consulting AB'

# Copyright statement for this module
Copyright = '(c) 2016 sgustafsson. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Powershell access to Everything - Blazingly fast file system searches'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = '5.0.0'

# Name of the Windows PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
DotNetFrameworkVersion = '4.5'

# Minimum version of the common language runtime (CLR) required by this module
# CLRVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @('PSEverything.dll')

# Functions to export from this module
FunctionsToExport = 'Select-EverythingString'

# Cmdlets to export from this module
CmdletsToExport = 'Search-Everything'

# Variables to export from this module
VariablesToExport = ''

# Aliases to export from this module
AliasesToExport = 'se','sles'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
FileList = 'Everything32.dll','Everything64.dll','LICENSE','PSEverything.dll','PSEverything.dll-Help.xml','PSEverything.psd1'

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = @('Search', 'Everything', 'voidtools', 'regex', 'grep')

        # A URL to the license for this module.
        LicenseUri = 'https://raw.githubusercontent.com/powercode/PSEverything/master/LICENSE'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/powercode/PSEverything'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = @'
2.1: Upgrading to SDK matching 1.4.1.809b  - Fixing hang when calling from Eleveated powershell
to Everything.
Now works with both eleveated and non-elevated processes as long as Everything is running as admin.       
2.0:
Implements tabcompletion.
Quoting filter paths
Requires PowerShell 5.0 or greater
1.3.3:
Really fixing issue where an error was written in Select-EverythingString when Search-Everything did not return any results        
1.3.2:
Fixing issue where an error was written in Select-EverythingString when Search-Everything did not return any results         
1.3.1:
Bug fix for -Filter that didn't work in combination with non-global searches.
'@

    } # End of PSData hashtable

} # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}

